HeadCraftEvent is not firing
Errored-Innovations/HeadsPlus pull request #102
Opened 2022-03-31 10:41 UTC by steve4744

Hi, I noticed that the `HeadCraftEvent` was not firing in v7.0.5, so had a look and found a possible fix for it. Also some issues with xp on crafting heads.

1) on crafting a head the `HeadCraftEvent` is never firing because `PlayerCraftListener` is exiting as `PersistenceManager.get().getSellType(e.getCurrentItem())` will return null/empty on a newly created head.

Checking for `CraftItemEvent` will allow the persistence data to be added, and the `HeadCraftEvent` will then fire correctly.

2) fixes the method for returning the number of craftable heads when shift-clicking the output slot of the crafting table.

3) restore the xp reward for crafting heads by adding a default to the config and calculating the xp based on number of heads crafted. 
This may help with #63 - not sure if there were other issues with crafting xp that I'm unaware of.

2022-03-31 11:03 UTC, Thatsmusic99 requested changes
Looks good, just asking for something to be double-checked with the persistence management.

2022-03-31 11:03 UTC, Thatsmusic99 commented on src/main/java/io/github/thatsmusic99/headsplus/listeners/PlayerCraftListener.java
> +            PersistenceManager.get().setSellType(e.getCurrentItem(), name.toUpperCase().replaceAll("[^A-Z]", ""));
Can I ask why this is being changed here and how come it's dependent on the display name of the item? That in itself doesn't feel reliable, the crafted item should have this set properly when initialised in the CraftingManager class, and could be hiding up a much larger issue.

2022-03-31 16:54 UTC, steve4744 commented on src/main/java/io/github/thatsmusic99/headsplus/listeners/LeaderboardListeners.java
> +                HPPlayer.getHPPlayer(player.getUniqueId()).addXp(MainConfig.get().getCraftingHeads().DEFAULT_CRAFTING_XP * event.getHeadsCrafted());
I can have a look at that and let you know if I can do it before the holidays.

2022-03-31 17:29 UTC, steve4744 commented on src/main/java/io/github/thatsmusic99/headsplus/listeners/PlayerCraftListener.java
> +            PersistenceManager.get().setSellType(e.getCurrentItem(), name.toUpperCase().replaceAll("[^A-Z]", ""));
Yes you are right, that makes sense.  I'll move it to the CraftingManager class where it can be set to the existing namespaceKey.
I just realised that my crafting.yml is way out of date and there a new things like lava buckets. This creates an an issue with the worldguard flag check for crafting non-entities, but I can try to update that too.
Thanks

2022-04-02 11:04 UTC, steve4744 commented on src/main/java/io/github/thatsmusic99/headsplus/listeners/LeaderboardListeners.java
> +                HPPlayer.getHPPlayer(player.getUniqueId()).addXp(MainConfig.get().getCraftingHeads().DEFAULT_CRAFTING_XP * event.getHeadsCrafted());
This was added in the final commit 5f7fd5b.

2022-04-02 11:05 UTC, steve4744 commented on src/main/java/io/github/thatsmusic99/headsplus/listeners/PlayerCraftListener.java
> +            PersistenceManager.get().setSellType(e.getCurrentItem(), name.toUpperCase().replaceAll("[^A-Z]", ""));
This was done in 6eb6b45

2022-04-06 09:24 UTC, Thatsmusic99 requested changes
One last thing and we should be good to go!

2022-04-06 09:24 UTC, Thatsmusic99 commented on src/main/java/io/github/thatsmusic99/headsplus/listeners/LeaderboardListeners.java
> +                HPPlayer.getHPPlayer(player.getUniqueId()).addXp(ConfigCrafting.get().getCraftingXp(key) * event.getHeadsCrafted());
Will admit, I'm not sure about this one either. The type should match the ID for fetching the crafting XP as well - I wanted to remove the need for all string manipulation. Is that not happening?

2022-04-06 09:24 UTC, Thatsmusic99 commented on src/main/java/io/github/thatsmusic99/headsplus/managers/CraftingManager.java
> +        PersistenceManager.get().setSellType(item, namespacedKey.toString());
Ohh, I see why you're doing the previous string manipulation - would it not be best to use just the key variable instead of flattening the namespaced key?

2022-04-06 09:24 UTC, Thatsmusic99 commented
Why has it duplicated some of my comments, rude

2022-04-10 12:28 UTC, steve4744 commented on src/main/java/io/github/thatsmusic99/headsplus/managers/CraftingManager.java
> +        PersistenceManager.get().setSellType(item, namespacedKey.toString());
Agree it would be cleaner to use the key variable - I took the way you'd set it in PlayerDeathListener, i.e. `PersistenceManager.get().setSellType(item, "mobs_PLAYER");` as guidance, so added "crafting_" to match "mobs_".

Happy to change it to use the key variable if you prefer? (sorry for the delay - been away).

2022-04-10 12:40 UTC, Thatsmusic99 commented
github really killin me right now

In that case, I forgot about the mobs_ prefix too, yeah, you can keep it as crafting then. I assume everything is resolved in that case; thank you once again!

2022-04-10 12:40 UTC, merged